# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

breeds = Breed.create([{ description: 'Affenpinscher' },
    { description: 'Afghan hound' },
    { description: 'Aidi' },
    { description: 'Airedale terrier' },
    { description: 'Akita americano' },
    { description: 'Akita Inu' },
    { description: 'American Pit Bull' },
    { description: 'American staffordshire terrier' },
    { description: 'Australian cattle dog' },
    { description: 'Australian silky terrier' },
    { description: 'Australian terrier' },
    { description: 'Azawakh' },
    { description: 'Azul da Gasconha' },
    { description: 'Barbet' },
    { description: 'Barzoi' },
    { description: 'Basenji' },
    { description: 'Basset Hound' },
    { description: 'Basset alemão da Vestfália' },
    { description: 'Basset alpino' },
    { description: 'Basset artesiano normando' },
    { description: 'Basset sueco' },
    { description: 'Beagle' },
    { description: 'Beagle Harrier' },
    { description: 'Bearded Collie' },
    { description: 'Beauceron' },
    { description: 'Bedlington terrier' },
    { description: 'Bergamasco' },
    { description: 'Bernese mountain dog' },
    { description: 'Bichon bolonhês' },
    { description: 'Bichon Frisé' },
    { description: 'Bichon havanês' },
    { description: 'Bichon maltês' },
    { description: 'Billy' },
    { description: 'Black and Tan terrier' },
    { description: 'Bloodhound' },
    { description: 'Bobtail' },
    { description: 'Boerboel' },
    { description: 'Boiadeiro Australiano' },
    { description: 'Boiadeiro Bernês' },
    { description: 'Boiadeiro de Appenzell' },
    { description: 'Boiadeiro de Entlebuch' },
    { description: 'Boiadeiro de Flandres' },
    { description: 'Border Collie' },
    { description: 'Border terrier' },
    { description: 'Borzoi' },
    { description: 'Boston terrier' },
    { description: 'Boxer' },
    { description: 'Braco alemão' },
    { description: 'Braco alemão de pêlo curto' },
    { description: 'Braco alemão de pêlo duro' },
    { description: 'Braco alemão de pêlo longo' },
    { description: 'Braco austríaco de pêlo liso' },
    { description: 'Braco de Ariège' },
    { description: 'Braco de Auvergne' },
    { description: 'Braco de Bourbon' },
    { description: 'Braco de Saint Germain' },
    { description: 'Braco de Weimar' },
    { description: 'Braco dinamarquês' },
    { description: 'Braco eslovaco de pêlo duro' },
    { description: 'Braco francês' },
    { description: 'Braco húngaro' },
    { description: 'Braco italiano' },
    { description: 'Braco polonês' },
    { description: 'Braco tirolês' },
    { description: 'Briard' },
    { description: 'Brittany' },
    { description: 'Broholmer' },
    { description: 'Buhund norueguês' },
    { description: 'Buldogue americano' },
    { description: 'Buldogue campeiro' },
    { description: 'Buldogue francês' },
    { description: 'Buldogue inglês' },
    { description: 'Bull Terrier' },
    { description: 'Bulldog americano' },
    { description: 'Bulldog campeiro' },
    { description: 'Bulldog francês' },
    { description: 'Bulldog inglês' },
    { description: 'Bulmastife' },
    { description: 'Cairn terrier' },
    { description: 'Cane Corso' },
    { description: 'Cão Anglo-Francês' },
    { description: 'Cão da Eurásia' },
    { description: 'Cão da Groenlêndia' },
    { description: 'Cão da Serra da Estrela' },
    { description: 'Cão da Serra de Aires' },
    { description: 'Cão de Artois' },
    { description: 'Cão de Bestiar' },
    { description: 'Cão de caça ao cervo sueco' },
    { description: 'Cão de Canaã' },
    { description: 'Cão de castro laboreiro' },
    { description: 'Cão de crista chinês' },
    { description: 'Cão de crista dorsal da Rodésia' },
    { description: 'Cão de guarda Holandês' },
    { description: ' Cão de Lontra' },
    { description: 'Cão de pista de sangue da Baviera' },
    { description: 'Cão de pista de sangue de Hanôver' },
    { description: 'Cão de presa maiorquino' },
    { description: 'Cão de santo Humberto' },
    { description: 'Cão de urso da Karélia' },
    { description: 'Cão do Ariège' },
    { description: 'Cão do Atlas' },
    { description: 'Cão do faraó' },
    { description: 'Cão dos Pirineus' },
    { description: 'Cão d’água americano' },
    { description: 'Cão d’água espanhol' },
    { description: 'Cão d’água frison' },
    { description: 'Cão d’água irlandês' },
    { description: 'Cão d’água português' },
    { description: 'Cão d’água romagnol' },
    { description: 'Cão finlandês da Lapônia' },
    { description: 'Cão Hokkaido' },
    { description: 'Cão Jindo da Coréia' },
    { description: 'Cão Lobo checoslovaco' },
    { description: 'Cão Lobo de Saarloos' },
    { description: 'Cão norueguês de Macareux' },
    { description: 'Cão pelado do Peru' },
    { description: 'Cão pelado Inca' },
    { description: 'Cão pelado Mexicano' },
    { description: 'Cão Tailandês de crista dorsal' },
    { description: 'Carlin' },
    { description: 'Cavalier king Charles spaniel' },
    { description: 'Chart polski' },
    { description: 'Chesapeake bay retriever' },
    { description: 'Chihuahua' },
    { description: 'Chinese crested' },
    { description: 'Chow Chow' },
    { description: 'Cirneco do Etna' },
    { description: 'Clumber spaniel' },
    { description: 'Cocker spaniel americano' },
    { description: 'Cocker spaniel inglês' },
    { description: 'Collie' },
    { description: 'Collie barbudo' },
    { description: 'Coonhound' },
    { description: 'Coton de Tulear' },
    { description: 'Curly-coated retriever' },
    { description: 'Dachbracke' },
    { description: 'Dachshund (Cofap)' },
    { description: 'Dachshund de pêlo curto' },
    { description: 'Dachshund de pêlo longo' },
    { description: 'Dálmata' },
    { description: 'Dandie Dinmont terrier' },
    { description: 'Deerhound' },
    { description: 'Dinamarquês' },
    { description: 'Doberman' },
    { description: 'Dogo argentino' },
    { description: 'Dogo canário' },
    { description: 'Dogue alemão' },
    { description: 'Dogue argentino' },
    { description: 'Dogue Brasileiro' },
    { description: 'Dogue de Bordeaux' },
    { description: 'Dogue de Maiorca' },
    { description: 'Dogue do Tibete' },
    { description: 'Dogue japonês' },
    { description: 'Drever' },
    { description: 'Dunker norueguês' },
    { description: 'Elkhound' },
    { description: 'Elkhound norueguês cinza' },
    { description: 'Elkhound norueguês preto' },
    { description: 'Falene' },
    { description: 'Field spaniel' },
    { description: 'Fila brasileiro' },
    { description: 'Flat-coated retriever' },
    { description: 'Fox paulistinha' },
    { description: 'Fox terrier' },
    { description: 'Foxhound americano' },
    { description: 'Foxhound inglês' },
    { description: 'Foxhound sueco' },
    { description: 'Francês' },
    { description: 'Fulvo da Bretanha' },
    { description: 'Galgo afegão' },
    { description: 'Galgo escocês' },
    { description: 'Galgo espanhol' },
    { description: 'Galgo húngaro' },
    { description: 'Galgo irlandês' },
    { description: 'Galgo italiano' },
    { description: 'Galgo persa' },
    { description: 'Galgo polonês' },
    { description: 'Galgo russo' },
    { description: 'Galgo tuaregue' },
    { description: 'Gascão Saintongeois' },
    { description: 'Glen' },
    { description: 'Golden retriever' },
    { description: 'Grande Boiadeiro suíço' },
    { description: 'Grande cão japonês' },
    { description: 'Grande Pirineus' },
    { description: 'Greyhound' },
    { description: 'Grifo Belga' },
    { description: 'Grifo checo' },
    { description: 'Grifo da Vendéia' },
    { description: 'Grifo de aponte de pêlo duro' },
    { description: 'Grifo italiano' },
    { description: 'Grifo nivernal' },
    { description: 'Halden stovare' },
    { description: 'Hamilton stovare' },
    { description: 'Harrier' },
    { description: 'Hokaido Ken' },
    { description: 'Hovawart' },
    { description: 'Husky siberiano' },
    { description: 'Ibizan hound' },
    { description: 'Iceland dog' },
    { description: 'Illirski Ovcar' },
    { description: 'Irish Glen of Imaal terrier' },
    { description: 'Irish soft-coated wheaten terrier' },
    { description: 'Irish water spaniel' },
    { description: 'Irish wolfhound' },
    { description: 'Italian greyhound' },
    { description: 'Jack Russel terrier' },
    { description: 'Jämthund' },
    { description: 'Kai Inu' },
    { description: 'Kai Ken' },
    { description: 'Kangal' },
    { description: 'Karelian Bear Dog' },
    { description: 'Kelpie' },
    { description: 'Kerry blue terrier' },
    { description: 'King Charles Spaniel' },
    { description: 'Kishu' },
    { description: 'Komondor' },
    { description: 'Kooiker' },
    { description: 'Kraski Ovcar' },
    { description: 'Kromfohrländer' },
    { description: 'Kurzhaar' },
    { description: 'Kuvasz' },
    { description: 'Kyushu' },
    { description: 'Labrador retriever' },
    { description: 'Laika' },
    { description: 'Lakeland terrier' },
    { description: 'Landseer' },
    { description: 'Lapinkoïra' },
    { description: 'Lapinporokoïra' },
    { description: 'Leonberger' },
    { description: 'Lhasa apso' },
    { description: 'Loup-chow' },
    { description: 'Lundehund' },
    { description: 'Löwchen' },
    { description: 'Magyar Agar' },
    { description: 'Malamute do Alasca' },
    { description: 'Maltês' },
    { description: 'Mastiff' },
    { description: 'Mastim do Tibete' },
    { description: 'Mastim dos pirineus' },
    { description: 'Mastim espanhol' },
    { description: 'Mastim inglês' },
    { description: 'Mastino napolitano' },
    { description: 'Mudi' },
    { description: 'Münsterländer' },
    { description: 'Norfolk terrier' },
    { description: 'Norwich terrier' },
    { description: 'Nova Scotia duck tolling retriever' },
    { description: 'Old English sheepdog' },
    { description: 'Otterhound' },
    { description: 'Ovelheiro Gaúcho' },
    { description: 'Papillon' },
    { description: 'Pastor Alemão' },
    { description: 'Pastor Alemão Branco' },
    { description: 'Pastor Australiano' },
    { description: 'Pastor Belga Groenandel' },
    { description: 'Pastor Belga Lakinois' },
    { description: 'Pastor Belga Malinois' },
    { description: 'Pastor Belga Tervuren' },
    { description: 'Pastor Bergamo' },
    { description: 'Pastor Branco Suíço' },
    { description: 'Pastor catalão' },
    { description: 'Pastor Croata' },
    { description: 'Pastor da Anatólia' },
    { description: 'Pastor da Ásia Central' },
    { description: 'Pastor da Catalunha' },
    { description: 'Pastor da Islândia' },
    { description: 'Pastor da Picárdia' },
    { description: 'Pastor da Rússia Meridional' },
    { description: 'Pastor de Beauce' },
    { description: 'Pastor de Brie' },
    { description: 'Pastor de Shetland' },
    { description: 'Pastor do Cáucaso' },
    { description: 'Pastor do Sul da Rússia' },
    { description: 'Pastor dos Pirineus' },
    { description: 'Pastor finlandês da Lapônia' },
    { description: 'Pastor Holandês' },
    { description: 'Pastor Iugoslavo' },
    { description: 'Pastor Maremmano Abruzzi' },
    { description: 'Pastor montanhês de Krast' },
    { description: 'Pastor norueguês' },
    { description: 'Pastor polonês de Podhal' },
    { description: 'Pastor polonês de planície' },
    { description: 'Pastor português da Serra de Aires' },
    { description: 'Pequeno cão holandês' },
    { description: 'Pequeno cão leão' },
    { description: 'Pequeno galgo italiano' },
    { description: 'Pequinês' },
    { description: 'Perdigueiro alemão' },
    { description: 'Perdigueiro de Burgos' },
    { description: 'Perdigueiro português' },
    { description: 'Pharaoh hound' },
    { description: 'Pinscher' },
    { description: 'Pinscher Austríaco de pêlo curto' },
    { description: 'Pit Bull' },
    { description: 'Podengo Ibecenco' },
    { description: 'Podengo português' },
    { description: 'Pointer inglês' },
    { description: 'Poitevin' },
    { description: 'Poodle' },
    { description: 'Poodle Toy' },
    { description: 'Porcelana' },
    { description: 'Pudelpointer' },
    { description: 'Pug' },
    { description: 'Puli' },
    { description: 'Pumi' },
    { description: 'Rafeiro do Alentejo' },
    { description: 'Retriever da Baía de Chesapeake' },
    { description: 'Retriever da Nova Escócia' },
    { description: 'Retriever de pêlo liso' },
    { description: 'Retriever de pêlo ondulado' },
    { description: 'Retriever do Labrador' },
    { description: 'Retriever dourado' },
    { description: 'Rhodesian' },
    { description: 'Rottweiler' },
    { description: 'Saarloos Wolfhound' },
    { description: 'Sabujo da Istria' },
    { description: 'Sabujo da Transilvânia' },
    { description: 'Sabujo de Halden' },
    { description: 'Sabujo de Hamilton' },
    { description: 'Sabujo de Posavatz' },
    { description: 'Sabujo de Schiller' },
    { description: 'Sabujo de Smaland' },
    { description: 'Sabujo de hygen' },
    { description: 'Sabujo eslovaco' },
    { description: 'Sabujo espanhol' },
    { description: 'Sabujo finlandês' },
    { description: 'Sabujo italiano' },
    { description: 'Sabujo iugoslavo' },
    { description: 'Sabujo suíço' },
    { description: 'Saluki' },
    { description: 'Samoieda' },
    { description: 'Schapendoes' },
    { description: 'Schiller stovare' },
    { description: 'Schipperke' },
    { description: 'Schnauzer' },
    { description: 'Scottish terrier' },
    { description: 'Sealyham terrier' },
    { description: 'Setter Gordon' },
    { description: 'Setter Irlandês' },
    { description: 'Setter inglês' },
    { description: 'Shar Pei' },
    { description: 'Sheep Dog' },
    { description: 'Shiba Inu' },
    { description: 'Shih tzu' },
    { description: 'Sidney terrier' },
    { description: 'Skye terrier' },
    { description: 'Sloughi' },
    { description: 'Slovensky Cuvac' },
    { description: 'Smaland Stovare' },
    { description: 'Smoushond' },
    { description: 'Spaniel anão continental' },
    { description: 'Spaniel azul da Picárdia' },
    { description: 'Spaniel Bretão' },
    { description: 'Spaniel da Picárdia' },
    { description: 'Spaniel de Pont-Audemar' },
    { description: 'Spaniel d’água irlandês' },
    { description: 'Spaniel francês' },
    { description: 'Spaniel Frison' },
    { description: 'Spaniel holandês' },
    { description: 'Spaniel japonês' },
    { description: 'Spaniel perdigueiro de Drenthe' },
    { description: 'Spaniel tibetano' },
    { description: 'Spinoni' },
    { description: 'Spitz alemão' },
    { description: 'Spitz da Lapônia' },
    { description: 'Spitz de Norboten' },
    { description: 'Spitz dos visigodos' },
    { description: 'Spitz finlandês' },
    { description: 'Spitz japonês' },
    { description: 'Springer spaniel galês' },
    { description: 'Springer spaniel inglês' },
    { description: 'Stabyhoun' },
    { description: 'Staffordshire bull terrier' },
    { description: 'Sussex spaniel' },
    { description: 'São Bernardo' },
    { description: 'Tazi' },
    { description: 'Teckel de pêlo curto' },
    { description: 'Teckel de pêlo duro' },
    { description: 'Teckel de pêlo longo' },
    { description: 'Terranova' },
    { description: 'Terrier alemão de caça' },
    { description: 'Terrier australiano' },
    { description: 'Terrier brasileiro' },
    { description: 'Terrier checo' },
    { description: 'Terrier de Boston' },
    { description: 'Terrier de seda' },
    { description: 'Terrier do Congo' },
    { description: 'Terrier escocês' },
    { description: 'Terrier irlandês' },
    { description: 'Terrier japonês' },
    { description: 'Terrier preto da Rússia' },
    { description: 'Terrier tibetano' },
    { description: 'Terrier trigueiro' },
    { description: 'Thaï Ridgeback' },
    { description: 'Tosa Inu' },
    { description: 'Toy Fox terrier' },
    { description: 'Toy Manchester terrier' },
    { description: 'Toy terrier preto e castanho' },
    { description: 'Vallhund sueco' },
    { description: 'Veadeiro Pampeano' },
    { description: 'Vizsla' },
    { description: 'Volpino' },
    { description: 'Vulpino Italiano' },
    { description: 'Xoloitzcuintle' },
    { description: 'Weimaraner' },
    { description: 'Welsh Corgi Cardigan' },
    { description: 'Welsh Corgi Pembroke' },
    { description: 'Welsh springer spaniel' },
    { description: 'Welsh terrier' },
    { description: 'West highland white terrier' },
    { description: 'Westie' },
    { description: 'Whippet' },
    { description: 'Yorkshire terrier' }]);

puts '--> Raças cadastradas';

# Array com os caracteres que representam os gêneros
genders = ['M', 'F'];

# Define o número de cachorros aleatórios que serão gerados
number_dogs = 1000;

number_dogs.times do |i|
    birthday = Faker::Date.between(3650.days.ago, 2.days.ago);
    date_last_visit = Faker::Date.between(birthday, Date.today);
    Dog.create(breed_id: rand(1..breeds.length), 
        gender: genders.sample, 
        castred: Faker::Boolean.boolean, 
        birthday: birthday, 
        name: Faker::Cat.name, # O 'Faker' não possui gerador de nomes de cachorro :(
        owner_name: Faker::Name.name, 
        owner_phone: Faker::PhoneNumber.cell_phone,
        date_last_visit: date_last_visit);
    puts '--> Cachorro aleatório nº #{i} cadastrado';
end